### PR TITLE
compat fix for Julia 1.12

### LINKED ISSUE #10: Errors on upcoming 1.12
Just saw this package error in a 1.12 PkgEval log so opening an issue. Haven't looked into it at all.

http://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c78016e_vs_d63aded/MistyClosures.primary.log

```
MistyClosures.jl: Error During Test at /home/pkgeval/.julia/packages/MistyClosures/4rFSA/test/runtests.jl:11
  Got exception outside of a @test
  sigtype mismatch in optimized opaque closure
  Stacktrace:
    [1] #generate_opaque_closure#4
      @ ./opaque_closure.jl:54 [inlined]
    [2] generate_opaque_closure
      @ ./opaque_closure.jl:47 [inlined]
    [3] OpaqueClosure(::Compiler.IRCode; isva::Bool, slotnames::Nothing, kwargs::@Kwargs{do_compile::Bool})
      @ Compiler ./../usr/share/julia/Compiler/src/opaque_closure.jl:55
    [4] OpaqueClosure
      @ ./../usr/share/julia/Compiler/src/opaque_closure.jl:30 [inlined]
    [5] MistyClosure(::Compiler.IRCode; kwargs::@Kwargs{do_compile::Bool})
      @ MistyClosures ~/.julia/packages/MistyClosures/4rFSA/src/MistyClosures.jl:19
    [6] top-level scope
      @ ~/.julia/packages/MistyClosures/4rFSA/test/runtests.jl:12
  
```

### PR DESCRIPTION
**Pull request by yebai**
Fix https://github.com/chalk-lab/MistyClosures.jl/issues/10

Julia's 1.12 update introduced stricter type checking for `OpaqueClosure`, which now correctly enforces that the closed-over variables must be passed within a `Tuple`. Previously, code could run by chance on version 1.11 because the memory layout of the closed-over object and the expected `Tuple` were the same, leading to a dangerous and incorrect execution. For example, to fix the issue, the callable object's first argument must be explicitly defined as a `Tuple{Foo}`, allowing it to correctly access the field `f[1].x` instead of `f.x`.

To illustrate how dangerous the behaviour in 1.11 was, consider this example (courtesy to @willtebbutt) 

```julia
julia> module MWE

       struct Foo
           x::Float64
       end

       (f::Foo)(y) = f.x * y

       f = Foo(4.0)
       ir_foo = Base.code_ircode_by_type(Tuple{Foo, Float64})[1][1];
       # ir_foo.argtypes[1] = Tuple{ir_foo.argtypes[1]}
       oc = Core.OpaqueClosure(ir_foo, 3, f; do_compile=true)
       @show oc(3.0)

       end
WARNING: replacing module MWE.
oc(3.0) = 4.4e-323
Main.MWE
```

This output is what you would get when you call `Core.bitcast(Float64, 3) * 3.0`, highlighting that the code was incorrectly using the closed-over integer `3` instead of the `Foo` object.

For example, to fix the issue, the callable object’s first argument must be explicitly defined as a `Tuple{Foo}`, allowing it to correctly access the field `f[1].x` instead of `f.x`.
The example below works correctly for both Julia 1.11 and 1.12:

```julia
julia> struct Foo
           x::Float64
       end

julia> (f::Tuple{Foo})(y) = f[1].x * y

julia> ir_foo = Base.code_ircode_by_type(Tuple{Tuple{Foo}, Float64})[1][1]
1 1 ─ %1 = $(Expr(:boundscheck, true))::Bool                                                              │╻ getindex
  │   %2 =   builtin Base.getfield(_1, 1, %1)::Foo                                                        ││
  │   %3 =   builtin Base.getfield(%2, :x)::Float64                                                       │╻ getproperty
  │   %4 = intrinsic Base.mul_float(%3, _2)::Float64                                                      │╻ *
  └──      return %4                                                                                      ││
                                                                                                            

julia> f = Foo(4.0)
Foo(4.0)

julia> oc = Core.OpaqueClosure(ir_foo, f; do_compile=true)
(::Float64)->◌::Float64

julia> oc(4.)
16.0
```

### CODE REVIEW

File: test/runtests.jl [hunk 1]
```diff
@@ -6,10 +6,13 @@ struct Foo
...
 
-(f::Foo)(y) = f.x * y
+# We wrap `Foo` inside `Tuple{Foo}` to satisfy opaque closure assumption 
+# that its first argument has to be a `Tuple` storing captured variables
+(f::Tuple{Foo})(y) = f[1].x * y
 
 @testset "MistyClosures.jl" begin
-    ir = Base.code_ircode_by_type(Tuple{typeof(sin), Float64})[1][1]
+    ir = Base.code_ircode_by_type(Tuple{typeof(sin), Float64}) |> only |> first
+    ir_foo.argtypes[1] = Tuple{}
```
Comment (yebai) [inline test/runtests.jl]:
```suggestion
    ir.argtypes[1] = Tuple{}
```

File: test/runtests.jl [hunk 2]
```diff
@@ -20,7 +23,7 @@ end
     @test @inferred(mc_default(5.0) == sin(5.0))
 
     # Recommended constructor with env.
-    ir_foo = Base.code_ircode_by_type(Tuple{Foo, Float64})[1][1]
+    ir_foo = Base.code_ircode_by_type(Tuple{Foo, Float64}) |> only |> first
```
Comment (yebai) [inline test/runtests.jl]:
```suggestion
    ir_foo = Base.code_ircode_by_type(Tuple{Tuple{Foo}, Float64}) |> only |> first
```
